### ISSUE TITLE
What happened to 'syllabus.md' in root directory?

### ISSUE THREAD

**Issue by AmritPatel** [cs50/ap#7]
When I navigate to https://ap.cs50.school/syllabus/, the page renders. When I go to my own site though it doesn't. When I look at '/curriculum/0/index.md', it indicates that there should be a 'syllabus.md' file in the root directory (i.e., '/syllabus' relative path is specified). Can you please add '/syllabus.md'? Thanks!

**Comment by Erin-c** [comment]
Hi @AmritPatel, sorry about that. We'll be adding an updated syllabus tomorrow.

**Comment by AmritPatel** [comment]
No worries and thank you for all that you are doing!

**Comment by Erin-c** [comment]
@AmritPatel Just added back syllabus.md
